language: java
jdk:
  - openjdk11

# Travis CI를 어느 브랜치가 푸시할 때 수행할 지 지정, (master로 push 될 때만 수행)
branches:
  only:
    - master

# gradle을 통해 의존성 받으면 이를 해당 디렉토리에 캐시, 같은 의존성은 다음 배포시 다시 안받도록 설정
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master branch로 push 될 때 수행하는 명령어(프로젝트의 gradlew를 통해 clean & build 수행)
script: "./gradlew clean build"

#deploy가 실행되기 전에 수행. CodeDeploy는 jar 인식 못하므로, jar + 기타 파일을 모아 zip으로 압축한다.
before_deploy:
  - zip -r springboot2-webservice *
  - mkdir -p deploy
  - mv springboot2-webservice.zip deploy/springboot2-webservice.zip

# s3로 파일 업로드 혹은 CodeDeploy로 배포 등 외부 서비스와 연동될 행위를 선언한다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY

    bucket: leejohy-springboot-build # s3 버킷
    region: ap-northest-2
    skip_cleanup: true
    acl : private # zip file 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리, 이 위치의 파일들만 s3로 전송한다.
    wait_until_deployed: true

# CI 실행 완료 시 메일로 알람. 빌드 queue에 걸려서 다시 Push
notifications:
  email:
    recipients:
      - leejohy@naver.com

